##### Informações Iniciais sobre o Dataset

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/heart.csv')

In [3]:
df.head()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0

In [4]:
df.tail()

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [5]:
df.sample(5)

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
205,50,M,ASY,150,215,0,Normal,140,Y,0.0,Up,0
422,65,M,ASY,150,236,1,ST,105,Y,0.0,Flat,1
350,53,M,ASY,120,0,1,Normal,120,N,0.0,Flat,1
540,62,M,NAP,138,204,0,ST,122,Y,1.2,Flat,1
265,54,M,ATA,160,305,0,Normal,175,N,0.0,Up,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 918 entries, 0 to 917
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Age             918 non-null    int64
 1   Sex             918 non-null    object
 2   ChestPainType   918 non-null    object
 3   RestingBP       918 non-null    int64
 4   Cholesterol     918 non-null    int64
 5   FastingBS       918 non-null    int64
 6   RestingECG      918 non-null    object
 7   MaxHR           918 non-null    int64
 8   ExerciseAngina  918 non-null    object
 9   Oldpeak         918 non-null    float64
 10  ST_Slope        918 non-null    object
 11  HeartDisease    918 non-null    int64
dtypes: float64(1), int64(6), object(5)
memory usage: 86.2+ KB

In [7]:
print(f"Colunas presentes: {df.columns}")

Colunas presentes: Index(['Age', 'Sex', 'ChestPainType', 'RestingBP', 'Cholesterol', 'FastingBS',
       'RestingECG', 'MaxHR', 'ExerciseAngina', 'Oldpeak', 'ST_Slope',
       'HeartDisease'],
      dtype='object')

In [8]:
print(f"Quantidade de Colunas: {df.shape[1]}")
print(f"Quantidade de Linhas: {df.shape[0]}")

Quantidade de Colunas: 12
Quantidade de Linhas: 918

In [9]:
print("Quantidade de valores nulos por coluna (Porcentagem)")
df.isnull().sum() / len(df)

Quantidade de valores nulos por coluna (Porcentagem)

Age               0.0
Sex               0.0
ChestPainType     0.0
RestingBP         0.0
Cholesterol       0.0
FastingBS         0.0
RestingECG        0.0
MaxHR             0.0
ExerciseAngina    0.0
Oldpeak           0.0
ST_Slope          0.0
HeartDisease      0.0
dtype: float64

In [10]:
df.describe(percentiles=[0, .25, .50, .75]).T.style.background_gradient(cmap='coolwarm')

In [11]:
print("Colunas categóricas:")

colunas_cat = df.select_dtypes(include=['object']).columns.to_list()
for col in df[colunas_cat]:
    print(f"\nColuna (Quantidade total): {col}\n{df[col].value_counts()}")
    print(f"\nColuna (Quantidade percentual): {col}\n{df[col].value_counts(normalize=True)}")

Colunas categóricas:

Coluna (Quantidade total): Sex
Sex
M    725
F    193
Name: count, dtype: int64

Coluna (Quantidade percentual): Sex
Sex
M    0.78976
F    0.21024
Name: proportion, dtype: float64

Coluna (Quantidade total): ChestPainType
ChestPainType
ASY    496
NAP    203
ATA    173
TA      46
Name: count, dtype: int64

Coluna (Quantidade percentual): ChestPainType
ChestPainType
ASY    0.540305
NAP    0.221133
ATA    0.188453
TA     0.050109
Name: proportion, dtype: float64

Coluna (Quantidade total): RestingECG
RestingECG
Normal    552
LVH       188
ST        178
Name: count, dtype: int64

Coluna (Quantidade percentual): RestingECG
RestingECG
Normal    0.601307
LVH       0.204793
ST        0.193900
Name: proportion, dtype: float64

Coluna (Quantidade total): ExerciseAngina
ExerciseAngina
N    547
Y    371
Name: count, dtype: int64

Coluna (Quantidade percentual): ExerciseAngina
ExerciseAngina
N    0.595861
Y    0.404139
Name: proportion, dtype: float64

Coluna (Quantidade total): ST_Slope
ST_Slope
Flat    460
Up      395
Down     63
Name: count, dtype: int64

Coluna (Quantidade percentual): ST_Slope
ST_Slope
Flat    0.501089
Up      0.430283
Down    0.068627
Name: proportion, dtype: float64

In [12]:
def contagem_outliers(df):
    colunas_num = df.select_dtypes(include=['int64', 'float64']).columns.to_list()
    outliers_count = {}
    for col in colunas_num:
        z_scores = np.abs((df[col] - df[col].mean()) / df[col].std())
        outliers = df[z_scores > 3]
        outliers_count[col] = len(outliers)
    return outliers_count

outliers_count = contagem_outliers(df)
print("Contagem de outliers utilizando Z-Score:")
for col, count in outliers_count.items():
    print(f"{col}: {count}")

Contagem de outliers utilizando Z-Score:
Age: 0
RestingBP: 8
Cholesterol: 3
FastingBS: 0
MaxHR: 1
Oldpeak: 7
HeartDisease: 0

In [13]:
colunas_num = [col for col in df.columns if df[col].dtype in ['int64', 'float64']]

print("\nQuantidade de outliers em cada coluna numérica utilizando Quartil:")
for col in colunas_num:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    outliers = df[(df[col] < (Q1 - 1.5 * IQR)) | (df[col] > (Q3 + 1.5 * IQR))]
    print(f"{col}: {outliers.shape[0]}")

Quantidade de outliers em cada coluna numérica utilizando Quartil:
Age: 0
RestingBP: 28
Cholesterol: 183
FastingBS: 214
MaxHR: 2
Oldpeak: 16
HeartDisease: 0

In [14]:
df_transformado = pd.read_csv("../data/dados_transformados.csv")

In [15]:
def correlacao_cor(val):
    if val >= 0.6 and val < 0.99999 or val <= -0.6 and val > -0.99999:
      color = 'red'
    elif val < 0.6 and val >= 0.3 or val > -0.6 and val <= -0.3:
      color = 'blue'
    elif val == 1:
       color = 'green'
    else:
        color = 'black'
    return 'color: %s' % color  

df_transformado.corr().style.applymap(correlacao_cor)

C:\Users\caioc\AppData\Local\Temp\ipykernel_17492\4140880459.py:12: FutureWarning: Styler.applymap has been deprecated. Use Styler.map instead.
  df_transformado.corr().style.applymap(correlacao_cor)

In [16]:
df_transformado.corr()['HeartDisease'].sort_values(key=abs, ascending=False)

HeartDisease         1.000000
ST_Slope_Up         -0.653759
ST_Slope_Flat        0.591554
ExerciseAngina       0.551834
Oldpeak              0.495696
MaxHR               -0.377212
ChestPainType_ATA   -0.375634
Age                  0.298617
Sex                  0.292779
ChestPainType_NAP   -0.222146
RestingBP            0.173242
FastingBS            0.160594
RestingECG_Normal   -0.133255
Cholesterol          0.103866
RestingECG_ST        0.095921
ChestPainType_TA    -0.053765
Name: HeartDisease, dtype: float64